# Generated by the monoban release (apps/cli/scripts/build-binaries.ts). Don't edit.
class Monoban < Formula
  desc "Keyboard-first kanban board, from your terminal"
  homepage "https://monoban.dev"
  version "1.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/thiagodmont/homebrew-tap/releases/download/monoban-v1.1.0/monoban-1.1.0-darwin-arm64.tar.gz"
      sha256 "f846a693589f1a7687b9bf9686284d76faa3a9f2a34df103d41ee16cc93b2ae0"
    end
    on_intel do
      url "https://github.com/thiagodmont/homebrew-tap/releases/download/monoban-v1.1.0/monoban-1.1.0-darwin-x64.tar.gz"
      sha256 "f795de7dec4b8360009887415050a2c36cc06dd42aa41c79ecfea4a7b422b134"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/thiagodmont/homebrew-tap/releases/download/monoban-v1.1.0/monoban-1.1.0-linux-arm64.tar.gz"
      sha256 "0136315b67133c0cead03b53de4f408c2a45737aac63409002df49a563f9cd96"
    end
    on_intel do
      url "https://github.com/thiagodmont/homebrew-tap/releases/download/monoban-v1.1.0/monoban-1.1.0-linux-x64.tar.gz"
      sha256 "f7b7eb588d38c82c157dc1f97a3d0a20665005b4b7d7fa12867f1074f37ce152"
    end
  end

  def install
    bin.install "monoban"
    generate_completions_from_executable(bin/"monoban", "completion")
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/monoban --version").strip
    assert_match "not signed in", shell_output("#{bin}/monoban whoami 2>&1", 4)
  end
end
