# Generated by the monoban release (apps/cli/scripts/build-binaries.ts). Don't edit.
class Monoban < Formula
  desc "Keyboard-first kanban board, from your terminal"
  homepage "https://monoban.dev"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/thiagodmont/homebrew-tap/releases/download/monoban-v0.1.0/monoban-0.1.0-darwin-arm64.tar.gz"
      sha256 "05d541a68e0f3a8f419f85855eb9e967b83f0cece9b032c14ffa4aa8a4cde059"
    end
    on_intel do
      url "https://github.com/thiagodmont/homebrew-tap/releases/download/monoban-v0.1.0/monoban-0.1.0-darwin-x64.tar.gz"
      sha256 "8b011ef96bd26e0ce348c7e99c6b7345a2919b6eaea4d6057e9b6d689440bb5a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/thiagodmont/homebrew-tap/releases/download/monoban-v0.1.0/monoban-0.1.0-linux-arm64.tar.gz"
      sha256 "36848da41f6f9105a51e1ab607c409465c82adfa47af0440dd7aa066070a7c1e"
    end
    on_intel do
      url "https://github.com/thiagodmont/homebrew-tap/releases/download/monoban-v0.1.0/monoban-0.1.0-linux-x64.tar.gz"
      sha256 "f5dfff7ee0fc288c7ae0ff8fd6c7e60fabe9917bc49e832d57987108b34a1b7b"
    end
  end

  def install
    bin.install "monoban"
    generate_completions_from_executable(bin/"monoban", "completion")
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/monoban --version").strip
    assert_match "not signed in", shell_output("#{bin}/monoban whoami 2>&1", 4)
  end
end
