# Generated by the monoban release (apps/cli/scripts/build-binaries.ts). Don't edit.
class Monoban < Formula
  desc "Keyboard-first kanban board, from your terminal"
  homepage "https://monoban.dev"
  version "1.0.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/thiagodmont/homebrew-tap/releases/download/monoban-v1.0.0/monoban-1.0.0-darwin-arm64.tar.gz"
      sha256 "cb772a8855e047e9140d2ec0def274a0ab27091fa0a415467eb7884085b2593a"
    end
    on_intel do
      url "https://github.com/thiagodmont/homebrew-tap/releases/download/monoban-v1.0.0/monoban-1.0.0-darwin-x64.tar.gz"
      sha256 "8a3b31835c1d2880812321bf3daa90ccb5ebcb3f92c969753943622ba6148245"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/thiagodmont/homebrew-tap/releases/download/monoban-v1.0.0/monoban-1.0.0-linux-arm64.tar.gz"
      sha256 "1ec1c699bd4511cbb032b94fcc2098f71dcb4d82f20927033172f759a2572694"
    end
    on_intel do
      url "https://github.com/thiagodmont/homebrew-tap/releases/download/monoban-v1.0.0/monoban-1.0.0-linux-x64.tar.gz"
      sha256 "13a684884d5b7ce8f53b91c522c23fa0d541febdaa8ca4accbea562641a16d02"
    end
  end

  def install
    bin.install "monoban"
    generate_completions_from_executable(bin/"monoban", "completion")
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/monoban --version").strip
    assert_match "not signed in", shell_output("#{bin}/monoban whoami 2>&1", 4)
  end
end
